version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: myblog-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: myblog
    networks:
      - myblog-network

  mongo-express:
    image: mongo-express:latest
    container_name: myblog-mongo-express
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password123
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - myblog-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: myblog-backend
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=development
      - PORT=5002
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/myblog?authSource=admin
      - JWT_SECRET=myblog_jwt_secret_key_2025
      - TEST_BYPASS_CAPTCHA_TOKEN=e2e_test_bypass_captcha_2025
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - myblog-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: myblog-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5002
      - REACT_APP_TEST_BYPASS_CAPTCHA_TOKEN=e2e_test_bypass_captcha_2025
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - myblog-network

volumes:
  mongodb_data:

networks:
  myblog-network:
    driver: bridge