version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: myblog-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: myblog
    networks:
      - myblog-network

  mongo-express:
    image: mongo-express:latest
    container_name: myblog-mongo-express
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password123
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - myblog-network

  minio:
    image: minio/minio:latest
    container_name: myblog-minio
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console UI port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - myblog-network

  minio-init:
    image: minio/mc:latest
    container_name: myblog-minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      mc alias set myminio http://minio:9000 minioadmin minioadmin123;
      mc mb myminio/blog-media --ignore-existing;
      mc anonymous set download myminio/blog-media;
      exit 0;
      "
    networks:
      - myblog-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: myblog-backend
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=development
      - PORT=5002
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/myblog?authSource=admin
      - JWT_SECRET=myblog_jwt_secret_key_2025
      - TEST_BYPASS_CAPTCHA_TOKEN=e2e_test_bypass_captcha_2025
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_USE_SSL=false
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      - MINIO_BUCKET=blog-media
      - MINIO_PUBLIC_URL=http://localhost:9000
      - MAX_FILE_SIZE=10485760
    depends_on:
      - mongodb
      - minio
    restart: unless-stopped
    networks:
      - myblog-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: myblog-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
     # - REACT_APP_TEST_MODE=true
      - REACT_APP_API_URL=http://localhost:5002/api
      - REACT_APP_TEST_BYPASS_CAPTCHA_TOKEN=e2e_test_bypass_captcha_2025
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - myblog-network

volumes:
  mongodb_data:
  minio_data:

networks:
  myblog-network:
    driver: bridge